// Code generated by Arduino IoT Cloud, ADD YOUR THING ID, SSID, AND PASS

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "CHANGE ME";  // Get from Arduino cloud

const char SSID[]     = "CHANGE ME";  // Network SSID (name)
const char PASS[]     = "CHANGE ME";  // Network password (use for WPA, or use as key for WEP)

void onWheatleyModeChange();

CloudSwitch wheatleyMode;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(wheatleyMode, READWRITE, ON_CHANGE, onWheatleyModeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
